Repository dry-frontend/dry-design-system, pull requests merged in 2023-05, with the labels that each got.

#24 UnderlinedText 컴포넌트를 구현한다.
  packages/payment/src/components/UnderlinedText/UnderlinedText.stories.tsx
  packages/payment/src/components/UnderlinedText/UnderlinedText.styled.tsx
  packages/payment/src/components/UnderlinedText/UnderlinedText.tsx
Labels: payments💳

#25 UnderlinedHeader 컴포넌트를 구현한다.
  packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.stories.tsx
  packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.styled.tsx
  packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.tsx
  packages/payment/src/styles/theme.ts
Labels: payments💳

#26 ColorChipButton 컴포넌트를 구현한다.
  packages/payment/src/components/ColorChipButton/ColorChipButton.stories.tsx
  packages/payment/src/components/ColorChipButton/ColorChipButton.styled.tsx
  packages/payment/src/components/ColorChipButton/ColorChipButton.tsx
Labels: payments💳

#28 Checkbox 컴포넌트를 구현한다.
  packages/payment/src/components/Checkbox/Checkbox.stories.tsx
  packages/payment/src/components/Checkbox/Checkbox.styled.tsx
  packages/payment/src/components/Checkbox/Checkbox.tsx
Labels: payments💳

#15 Thumbnail 컴포넌트를 구현한다.
  packages/cart/src/components/Thumbnail/Thumbnail.stories.tsx
  packages/cart/src/components/Thumbnail/Thumbnail.tsx
  packages/cart/src/components/Thumbnail/styles.ts
  packages/cart/src/components/Thumbnail/types.d.ts
Labels: cart

#8 피그마 시안에 맞도록 Button 컴포넌트를 리팩터링한다.
  packages/cart/src/assets/cart.svg
  packages/cart/src/assets/fillCart.svg
  packages/cart/src/components/Button/Button.stories.tsx
  packages/cart/src/components/Button/Button.tsx
  packages/cart/src/components/Button/getButtonSize.ts
  packages/cart/src/components/Button/styles.ts
  packages/cart/src/components/Button/types.d.ts
  packages/cart/src/components/Icon/Icon.stories.tsx
  packages/cart/src/components/Icon/Icon.tsx
  packages/cart/src/components/Icon/styles.ts
  packages/cart/src/components/IconButton/IconButton.stories.tsx
  packages/cart/src/components/IconButton/IconButton.tsx
  packages/cart/src/components/IconButton/styles.ts
  packages/cart/src/components/LoadingSpinner/LoadingSpinner.tsx
  packages/cart/src/components/LoadingSpinner/styles.ts
  packages/cart/src/components/chip/Chip.stories.tsx
  packages/cart/src/components/chip/Chip.tsx
  packages/cart/src/components/chip/styles.ts
  pnpm-lock.yaml
Labels: cart

#16 FlexBox, Text, Stepper 컴포넌트 구현
  packages/cart/package.json
  packages/cart/src/components/Button/PlainButton.tsx
  packages/cart/src/components/FlexBox/FlexBox.stories.tsx
  packages/cart/src/components/FlexBox/FlexBox.tsx
  packages/cart/src/components/Stepper/Stepper.stories.tsx
  packages/cart/src/components/Stepper/Stepper.tsx
  packages/cart/src/components/Stepper/styles.ts
  packages/cart/src/components/Text/Text.stories.tsx
  packages/cart/src/components/Text/Text.tsx
  packages/cart/src/styles/globals.css
  pnpm-lock.yaml
Labels: cart

#17 checkbox 컴포넌트를 구현한다.
  packages/cart/src/App.tsx
  packages/cart/src/assets/check.svg
  packages/cart/src/components/Checkbox/Checkbox.stories.tsx
  packages/cart/src/components/Checkbox/Checkbox.tsx
  packages/cart/src/components/Checkbox/styles.ts
  pnpm-lock.yaml
Labels: cart

#10 FlexBox 구현한다
  packages/payment/src/components/FlexBox/FlexBox.stories.tsx
  packages/payment/src/components/FlexBox/FlexBox.styled.tsx
  packages/payment/src/components/FlexBox/FlexBox.tsx
Labels: payments💳, release-w19

#37 [To Main] Release w19 To Main (5/14)
  packages/cart/package.json
  packages/cart/src/App.tsx
  packages/cart/src/assets/cart.svg
  packages/cart/src/assets/check.svg
  packages/cart/src/assets/fillCart.svg
  packages/cart/src/components/Button/Button.stories.tsx
  packages/cart/src/components/Button/Button.tsx
  packages/cart/src/components/Button/PlainButton.tsx
  packages/cart/src/components/Button/getButtonSize.ts
  packages/cart/src/components/Button/styles.ts
  packages/cart/src/components/Button/types.d.ts
  packages/cart/src/components/Checkbox/Checkbox.stories.tsx
  packages/cart/src/components/Checkbox/Checkbox.tsx
  packages/cart/src/components/Checkbox/styles.ts
  packages/cart/src/components/FlexBox/FlexBox.stories.tsx
  packages/cart/src/components/FlexBox/FlexBox.tsx
  packages/cart/src/components/Icon/Icon.stories.tsx
  packages/cart/src/components/Icon/Icon.tsx
  packages/cart/src/components/Icon/styles.ts
  packages/cart/src/components/IconButton/IconButton.stories.tsx
  packages/cart/src/components/IconButton/IconButton.tsx
  packages/cart/src/components/IconButton/styles.ts
  packages/cart/src/components/LoadingSpinner/LoadingSpinner.tsx
  packages/cart/src/components/LoadingSpinner/styles.ts
  packages/cart/src/components/Stepper/Stepper.stories.tsx
  packages/cart/src/components/Stepper/Stepper.tsx
  packages/cart/src/components/Stepper/styles.ts
  packages/cart/src/components/Text/Text.stories.tsx
  packages/cart/src/components/Text/Text.tsx
  packages/cart/src/components/Thumbnail/Thumbnail.stories.tsx
  packages/cart/src/components/Thumbnail/Thumbnail.tsx
  packages/cart/src/components/Thumbnail/styles.ts
  packages/cart/src/components/Thumbnail/types.d.ts
  packages/cart/src/components/chip/Chip.stories.tsx
  packages/cart/src/components/chip/Chip.tsx
  packages/cart/src/components/chip/styles.ts
  packages/cart/src/styles/globals.css
  packages/payment/src/components/Checkbox/Checkbox.stories.tsx
  packages/payment/src/components/Checkbox/Checkbox.styled.tsx
  packages/payment/src/components/Checkbox/Checkbox.tsx
  packages/payment/src/components/ColorChipButton/ColorChipButton.stories.tsx
  packages/payment/src/components/ColorChipButton/ColorChipButton.styled.tsx
  packages/payment/src/components/ColorChipButton/ColorChipButton.tsx
  packages/payment/src/components/FlexBox/FlexBox.stories.tsx
  packages/payment/src/components/FlexBox/FlexBox.styled.tsx
  packages/payment/src/components/FlexBox/FlexBox.tsx
  packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.stories.tsx
  packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.styled.tsx
  packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.tsx
  packages/payment/src/components/UnderlinedText/UnderlinedText.stories.tsx
  packages/payment/src/components/UnderlinedText/UnderlinedText.styled.tsx
  packages/payment/src/components/UnderlinedText/UnderlinedText.tsx
  packages/payment/src/styles/theme.ts
  pnpm-lock.yaml
Labels: To Main

#27 Carousel 컴포넌트를 구현한다.
  packages/payment/src/assets/arrow.svg
  packages/payment/src/components/Carousel/Carousel.stories.tsx
  packages/payment/src/components/Carousel/Carousel.styled.tsx
  packages/payment/src/components/Carousel/Carousel.tsx
Labels: payments💳, release-w20

#29 Drawer 컴포넌트를 구현한다
  packages/payment/src/components/Drawer/Drawer.stories.tsx
  packages/payment/src/components/Drawer/Drawer.styled.tsx
  packages/payment/src/components/Drawer/Drawer.tsx
Labels: payments💳, release-w20

#31 ToolTip컴포넌트를 구현한다
  packages/payment/src/components/ToolTip/ToolTip.stories.tsx
  packages/payment/src/components/ToolTip/ToolTip.styled.tsx
  packages/payment/src/components/ToolTip/ToolTip.tsx
  packages/payment/src/components/ToolTip/TooltipContext.ts
Labels: payments💳, release-w20

#32 Input 컴포넌트를 구현한다
  packages/payment/src/components/Input/CardNumberInput/CardNumberInput.stories.tsx
  packages/payment/src/components/Input/CardNumberInput/CardNumberInput.styled.tsx
  packages/payment/src/components/Input/CardNumberInput/CardNumberInput.tsx
  packages/payment/src/components/Input/CvcInput/CvcInput.stories.tsx
  packages/payment/src/components/Input/CvcInput/CvcInput.styled.tsx
  packages/payment/src/components/Input/CvcInput/CvcInput.tsx
  packages/payment/src/components/Input/ExpirationDateInput/ExpirationDateInput.stories.tsx
  packages/payment/src/components/Input/ExpirationDateInput/ExpirationDateInput.styled.tsx
  packages/payment/src/components/Input/ExpirationDateInput/ExpirationDateInput.tsx
  packages/payment/src/components/Input/Input.styled.tsx
  packages/payment/src/components/Input/NameInput/NameInput.stories.tsx
  packages/payment/src/components/Input/NameInput/NameInput.styled.tsx
  packages/payment/src/components/Input/NameInput/NameInput.tsx
  packages/payment/src/components/Input/PasswordInput/PasswordInput.stories.tsx
  packages/payment/src/components/Input/PasswordInput/PasswordInput.styled.tsx
  packages/payment/src/components/Input/PasswordInput/PasswordInput.tsx
  packages/payment/src/components/Input/inputType.ts
Labels: payments💳, release-w20

#35 Card 를 구현한다.
  packages/payment/src/components/Card/Card.stories.tsx
  packages/payment/src/components/Card/Card.styled.ts
  packages/payment/src/components/Card/Card.tsx
Labels: payments💳, release-w20

#40 Header 컴포넌트를 구현한다.
  packages/payment/src/components/Header/Header.stories.tsx
  packages/payment/src/components/Header/Header.styled.tsx
  packages/payment/src/components/Header/Header.tsx
  packages/payment/src/components/ToolTip/TooltipContext.tsx
Labels: payments💳, release-w20

#38 [To Main] Release w20 To Main (5/21)
  packages/payment/src/assets/arrow.svg
  packages/payment/src/assets/arrow1.png
  packages/payment/src/components/Card/Card.stories.tsx
  packages/payment/src/components/Card/Card.styled.ts
  packages/payment/src/components/Card/Card.tsx
  packages/payment/src/components/Carousel/Carousel.stories.tsx
  packages/payment/src/components/Carousel/Carousel.styled.tsx
  packages/payment/src/components/Carousel/Carousel.tsx
  packages/payment/src/components/Drawer/Drawer.stories.tsx
  packages/payment/src/components/Drawer/Drawer.styled.tsx
  packages/payment/src/components/Drawer/Drawer.tsx
  packages/payment/src/components/Header/Header.stories.tsx
  packages/payment/src/components/Header/Header.styled.tsx
  packages/payment/src/components/Header/Header.tsx
  packages/payment/src/components/Input/CardNumberInput/CardNumberInput.stories.tsx
  packages/payment/src/components/Input/CardNumberInput/CardNumberInput.styled.tsx
  packages/payment/src/components/Input/CardNumberInput/CardNumberInput.tsx
  packages/payment/src/components/Input/CvcInput/CvcInput.stories.tsx
  packages/payment/src/components/Input/CvcInput/CvcInput.styled.tsx
  packages/payment/src/components/Input/CvcInput/CvcInput.tsx
  packages/payment/src/components/Input/ExpirationDateInput/ExpirationDateInput.stories.tsx
  packages/payment/src/components/Input/ExpirationDateInput/ExpirationDateInput.styled.tsx
  packages/payment/src/components/Input/ExpirationDateInput/ExpirationDateInput.tsx
  packages/payment/src/components/Input/Input.styled.tsx
  packages/payment/src/components/Input/NameInput/NameInput.stories.tsx
  packages/payment/src/components/Input/NameInput/NameInput.styled.tsx
  packages/payment/src/components/Input/NameInput/NameInput.tsx
  packages/payment/src/components/Input/PasswordInput/PasswordInput.stories.tsx
  packages/payment/src/components/Input/PasswordInput/PasswordInput.styled.tsx
  packages/payment/src/components/Input/PasswordInput/PasswordInput.tsx
  packages/payment/src/components/Input/inputType.ts
  packages/payment/src/components/ToolTip/ToolTip.stories.tsx
  packages/payment/src/components/ToolTip/ToolTip.styled.tsx
  packages/payment/src/components/ToolTip/ToolTip.tsx
  packages/payment/src/components/ToolTip/TooltipContext.ts
  packages/payment/src/components/ToolTip/TooltipContext.tsx
  packages/payment/src/components/buttons/Button/Button.stories.tsx
  packages/payment/src/components/buttons/Button/Button.styled.ts
  packages/payment/src/components/buttons/Button/Button.tsx
  packages/payment/src/components/buttons/IconButton/IconButton.stories.tsx
  packages/payment/src/components/buttons/IconButton/IconButton.styled.ts
  packages/payment/src/components/buttons/IconButton/IconButton.tsx
  packages/payment/src/styles/theme.ts
Labels: To Main

#36 버튼 padding 관리 방식을 확장성 있도록 변경
  packages/cart/src/components/Button/Button.tsx
  packages/cart/src/components/Button/getButtonSize.ts
  packages/cart/src/components/Button/styles.ts
  packages/cart/src/components/Button/types.d.ts
  packages/cart/src/components/Chip/Chip.tsx
  packages/cart/src/components/chip/Chip.stories.tsx
Labels: cart, release-w21
